version: '3.5'
services:
  api1: &api
    image: opencodeco/rinha-de-backend:2023-q3
    environment:
      DB_HOST: db
      DB_DATABASE: rinha
      DB_USERNAME: root
      DB_PASSWORD: rinha
      REDIS_HOST: cache
    depends_on:
      - db
      - cache
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.7GB'

  api2:
    <<: *api

  db:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
    environment:
      MYSQL_ROOT_PASSWORD: rinha
      MYSQL_DATABASE: rinha

  cache:
    image: redis:7.2
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.1GB'
