version: "3.5"
services:
  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rinhadb
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "0.5GB"
    volumes:
      - ./inital.sql:/docker-entrypoint-initdb.d/init.sql

  cache:
    hostname: cache
    image: redis:latest
    command: redis-server --save "" --appendonly no
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.06'
          memory: '0.5GB'

  api1: # API - Instância 01
    image: luiscarlosb3/rinhabackend:latest
    hostname: api1
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.37'
          memory: '0.9GB'

  api2: # API - Instância 02
    image: luiscarlosb3/rinhabackend:latest
    hostname: api2
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.37'
          memory: '0.9GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.2GB'

volumes:
  rinha-db:

networks:
  default:
    driver: bridge