version: '3.9'

services:
  api1: &api
    build:
      context: .
    container_name: api1
    command: "bundle exec puma -s --preload -w 2 -p 3000"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'

  api2: 
    <<: *api
    container_name: api2

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1.5GB'

  nginx:
    image: nginx 
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'
