version: "3.5"
services:
  api1:
    image: carlosalm/desafio-rinha-de-backend-2023-q3:latest
    hostname: api1
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - db
      - redis
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "0.7GB"

  api2:
    image: carlosalm/desafio-rinha-de-backend-2023-q3:latest
    hostname: api2
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - db
      - redis
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "0.7GB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.3GB"

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "0.8GB"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.5GB"
