version: '3.4'
services:
  postgres:
      image: postgres
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345678
      ports:
        - 5432:5432
      deploy:
        resources:
          limits:
            cpus: '0.4'
            memory: '0.5GB'
  app1:
      image: lukas8219/rinha-be-2023-q3:latest
      environment:
        DB_URL: "postgres://postgres:12345678@postgres:5432/postgres"
        REDIS_URL: "redis://redis"
        BATCH: "false"
        CLUSTER: "false"
        PINO_LOG_LEVEL: "info"
        REQ_TIMEOUT: "10000"
      ports:
        - "8080"
      depends_on:
        - postgres
        - redis
      deploy:
        resources:
          limits:
            cpus: '0.3'
            memory: '0.2GB'
  app2:
      image: lukas8219/rinha-be-2023-q3:latest
      environment:
        DB_URL: "postgres://postgres:12345678@postgres:5432/postgres"
        REDIS_URL: "redis://redis"
        BATCH: "false"
        CLUSTER: "false"
        REQ_TIMEOUT: "10000"
        PINO_LOG_LEVEL: "info"
      ports:
        - "8080"
      depends_on:
        - postgres
        - redis
      deploy:
        resources:
          limits:
            cpus: '0.3'
            memory: '0.2GB'
  app3:
      image: lukas8219/rinha-be-2023-q3:latest
      environment:
        DB_URL: "postgres://postgres:12345678@postgres:5432/postgres"
        REDIS_URL: "redis://redis"
        BATCH: "false"
        CLUSTER: "false"
        REQ_TIMEOUT: "10000"
        PINO_LOG_LEVEL: "info"
      ports:
        - "8080"
      depends_on:
        - postgres
        - redis
      deploy:
        resources:
          limits:
            cpus: '0.3'
            memory: '0.2GB'
  redis: # Load Balancer
    image: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'
  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'